---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-engine-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: engine
            image: ghcr.io/ponkio/sync_engine:0.1.0
            imagePullPolicy: Always
            command:
            - /usr/local/bin/python 
            - /app/main.py 
            - -s 
            - 0 * * * *
            env:
              - name: MONGO_PWD
                valueFrom:
                  secretKeyRef:
                    name: mongo-pwd
                    key: root-pwd
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-engine-daily
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: engine
            image: ghcr.io/ponkio/sync_engine:0.1.0
            imagePullPolicy: Always
            command:
            - /usr/local/bin/python 
            - /app/main.py 
            - -s 
            - 0 0 * * *
            env:
              - name: MONGO_PWD
                valueFrom:
                  secretKeyRef:
                    name: mongo-pwd
                    key: root-pwd
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-engine-weekly
spec:
  schedule: "0 0 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: engine
            image: ghcr.io/ponkio/sync_engine:0.1.0
            imagePullPolicy: Always
            command:
            - /usr/local/bin/python 
            - /app/main.py 
            - -s 
            - 0 0 * * 5
            env:
              - name: MONGO_PWD
                valueFrom:
                  secretKeyRef:
                    name: mongo-pwd
                    key: root-pwd
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred
---